config/routes.rb
Rails.application.routes.draw do

  get  '/dogs', to: 'dogs#index'
  get '/dogs/new', to: 'dogs#new', as: 'new_dog' 
  post '/dogs', to: 'dogs#create' 
  get '/dogs/:id', to: 'dogs#show', as: 'dog'
  get '/dogs/:id/edit', to: 'dogs#edit', as: 'edit_dog'
  put '/dogs/:id', to: 'dogs#update'
  patch '/dogs/:id', to: 'dogs#update'
  delete '/dogs/:id', to: 'dogs#destroy'

end

app/models/dog.rb
class Dog < ActiveRecord::Base


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
 
	def index
		@dogs = Dog.all
	end

	def new
		@dog = Dog.new
	end

	def create
		@dog = Dog.new(params.require(:dog).permit!)
		if @dog.save 
			flash[:notice] = "New dog succesfully created"
			redirect_to dogs_path
		else
			render 'new'
		end
	end

	def edit
		@dog = Dog.find(params[:id])
	end

	def update
		@dog = Dog.find(params[:id])
		if @dog.update(params.require(:dog).permit!)
			flash[:notice] = "Dog was updated succesfuly"
			redirect_to dogs_path
		else
			render 'edit'
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

def dog_info(dog)
	"#{dog.name} is #{dog.height_in_inches} inches tall and weighs #{dog.weight_in_lbs}"
end

end

app/views/dogs/_form.html.erb
<%= form_for @dog do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br/>
	<%= f.label :height_in_inches, 'Height' %>
	<%= f.text_field :height_in_inches %>
	<br/>
	<%= f.label :weight_in_lbs, 'Weight' %>
	<%= f.text_field :weight_in_lbs %>
	<br/>
	<%= f.submit(@dog.new_record? ? 'Create Dog' : 'Edit the dog') %>
<% end %>

app/views/dogs/edit.html.erb
<h2>Edit your dog</h2>

<%= render 'form' %>

app/views/dogs/index.html.erb
<%= link_to 'Create a new Dog', new_dog_path %> 

<h2>All the dogs!</h2>

<% @dogs.each do |dog| %>
	<ul>
		<li><%= dog_info(dog) %> <%= link_to 'edit this dog', edit_dog_path(dog) %></li>
	</ul>
<% end %>

app/views/dogs/new.html.erb
<h2>Create a new dog</h2>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>